"""Add recipient fields to Order model

Revision ID: 6c6a79061b1c
Revises: 
Create Date: 2025-01-09 14:56:21.787224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6a79061b1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('recipient_address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('recipient_phone', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('recipient_phone')
        batch_op.drop_column('recipient_address')
        batch_op.drop_column('recipient_name')

    # ### end Alembic commands ###
